<?php
/**
 * Copyright © Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */

/** @var $block Klarna\Base\Block\Info\Klarna */
$_specificInfo = $block->getSpecificInformation()
?>

<?php if (!$block->isB2bOrder()): ?>
<p><img width="150"
        src="<?= /* @noEscape */ $block->getLogoUrl() ?>"
        alt="<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>"/></p>
<?php endif; ?>

<?php if ($_specificInfo): ?>
    <table>
        <tbody>
        <?php /* @noEscape */ foreach ($_specificInfo as $_label => $_value): ?>
            <?php $implodedValue = implode("\n", $block->getValueAsArray($_value, true)); ?>
            <tr>
                <th><strong><?= $block->escapeHtml($_label) ?>:</strong></th>
            </tr>
            <tr>
                <td><?= /* @noEscape */ nl2br($block->escapeHtml($implodedValue)) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?= $block->getChildHtml() ?>
